FROM python:3.5.6
WORKDIR /app

COPY ./ensembl-prodinf-srv/requirements.txt /app/requirements.txt
COPY ./ssh /root/.ssh
RUN pip install -r requirements.txt

ENV PYTHONPATH="/app/ensembl-prodinf-core:/app/ensembl-prodinf-srv"

WORKDIR /app/ensembl-prodinf-srv

RUN ssh-keyscan -H 10.7.95.60 >> ~/.ssh/known_hosts
RUN ssh-keyscan -H 172.22.10.207 >> ~/.ssh/known_hosts

CMD ["celery", "-A", "ensembl_prodinf.event_tasks worker" , "-l",  "info", "-Q", "qrp", "-n", "qrp-handover@%%h"]
